version: "3"
services:

  web:
      build: ./
      env_file:
        - ./backend/.env
      environment:
        DB_HOST: db
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: root
      command: >
          bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
      ports:
          - 8000:8000
      volumes:
          - ./backend:/app
      depends_on:
        - db
      networks:
        - app-network

  worker:
    build: ./
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    command: php artisan queue:listen
    ports:
        - 8001:8000
    volumes:
        - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network
  db:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
      volumes:
        - ./db_init:/docker-entrypoint-initdb.d
        - ./mariadb:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge